GET http://localhost:3001/api/blogs

### POST
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Lily's Blog",
  "author": "Lily Z",
  "url": "www.lilyisdabest.com",
  "likes": 12
}

### Unknown endpoint
GET http://localhost:3001/api/wtf

### Bad request
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Lily's Blog",
  "author": "Lily Z",
  "url": "www.lilyisdabest.com",
  "likes": 12
}