### Create new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "lilyz92",
  "name": "Lily Z",
  "password": "chocolate123"
}

### Create new user ERROR: username / password too short
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mialein92+",
  "name": "Mifa Lin",
  "password": "chfdfeas"
}

### DELETE user
DELETE http://localhost:3001/api/users/603048ba51c2c25243183a8e