GET http://localhost:3001/api/blogs

### POST
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Lily's Blog",
  "author": "Lily Z",
  "url": "www.lilyisdabest.com",
  "likes": 12
}

### PUT
PUT http://localhost:3001/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json

{
  "title": "God I love cats",
  "likes": 42069
}

### Unknown endpoint
GET http://localhost:3001/api/wtf

### Bad request
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Lily's Blog",
  "author": "Lily Z",
  "url": "www.lilyisdabest.com",
  "likes": 12
}